language: python
python: 3.7.9
dist: xenial
sudo: true
install:
  - sudo apt-get update || true
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda || true
  # Useful for debugging any issues with conda
  - conda info -a
  # Increasing stack size because stackoverflow told me to
  - ulimit -s 82768 
  # Useful for debugging memory issues
  - ulimit -a
  - free -m
  - conda env create -vv -n test-environment -f binder/environment.yml
  - source activate test-environment
  #Packages for testing only -- don't need in user environment.
  - pip3 install codecov pytest==7.1.3 pytest-cov pytest_notebook nbval==0.9.6 papermill
  - ipython kernel install --user --name=galactic-spin 

before_script: cd binder
script:
- pytest --cov=./ --cov-report=xml --nbval --current-env --cov-config=../.coveragerc
- papermill --prepare-only -p galaxy NGC5533 07_Bonus_Bulge_Rotation_Curve.ipynb 07_Bonus_Bulge_Rotation_Curve_NGC5533.ipynb
- papermill --prepare-only -p galaxy NGC7814 07_Bonus_Bulge_Rotation_Curve.ipynb 07_Bonus_Bulge_Rotation_Curve_NGC7814.ipynb
- pytest --cov=./ --cov-report=xml --nbval-lax 07_Bonus_Bulge_Rotation_Curve_NGC????.ipynb --cov-append --current-env --cov-config=../.coveragerc
after_script:
- codecov