name: galactic-spin 
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.9
  - matplotlib==3.5.1
  - h5py==3.7.0
  - ipywidgets==8.0.4
  - pip
  - ipykernel
  - pip:
    - numpy
    - scipy
    - lmfit
    - sympy
    - astroquery
    - dataPython
    - mpld3
    - ipympl
    - ipylab
    - ffmpeg
  - jupyterlab==3.4.3
