name: galactic-spin 
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.7
  - h5py==3.14.0
  - pip
  - pip:
    - scipy==1.16.1
    - lmfit==1.3.4
    - sympy==1.14.0
    - astroquery==0.4.10
    - mpld3==0.5.10
    - ipympl==0.9.7
    - ipylab==1.0.0
    - ffmpeg-python==0.2.0
    - jupyterlab==4.4.5
    - matplotlib==3.10.3
    - ipywidgets==8.1.7
    - joblib==1.5.1
    - pytest==8.3.4
    - nbval==0.11.0
    - papermill==2.7.0
