on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: TeX
        uses: docker://openjournals/paperdraft:latest
        with:
          args: paper/paper.md --to=latex --output=paper.tex
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: jose
      - name: PDF
        uses: docker://openjournals/paperdraft:latest
        with:
          args: paper/paper.md
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: jose
      - uses: actions/upload-artifact@v3
        with:
          path: paper
