on:
  push:
    branches: [ main ]
    paths: [ 'paper/**' ]
  pull_request:
    paths: [ 'paper/**' ]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Build Paper PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: jose
          paper-path: paper/paper.md
      
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-${{ github.sha }}
          path: paper/paper.pdf
          retention-days: 30
